### ISSUE TITLE
WeakAurasModelPaths in classic archive

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#2011]
## Describe the bug
WeakAurasModelPaths folder is ignored in .pkgmeta-classic but still show in packaged zip

```
ignore:
  - README.md
  - CONTRIBUTING.md
  - babelfish.lua
  - wowace_translations.sh
  - generate_changelog.sh
  - WeakAuras/RegionTypes/Model.lua
  - WeakAurasOptions/RegionOptions/Model.lua
  - WeakAuras/WeakAurasTemplates
  - WeakAuras/WeakAurasModelPaths

move-folders:
  WeakAuras/WeakAuras: WeakAuras
  WeakAuras/WeakAurasOptions: WeakAurasOptions
  WeakAuras/WeakAurasTemplates: WeakAurasTemplates
  WeakAuras/WeakAurasArchive: WeakAurasArchive
```

Curseforge last alpha
https://www.curseforge.com/wow/addons/weakauras-2/download/2887468
https://i.imgur.com/Gso6uIq.png
https://i.imgur.com/jWMyoYx.png

Also archives generated in last Infus's PR have 2 copy of this folder
https://github.com/WeakAuras/WeakAuras2/suites/478179941/artifacts/2172524 
https://i.imgur.com/pMg9h46.png
https://i.imgur.com/IttPEXZ.png
